FROM python:3.5-alpine

# Required to install uwsgi and git sources
RUN apk add --no-cache --virtual .fetch-deps \
  git \
  python3-dev \
  libffi-dev \
  libffi \
  openssl \
  openssl-dev \
  py-cffi \
  build-base \
  linux-headers \
  pcre-dev && rm -rf /var/cache/apk/*

RUN adduser -D -g '' celery_worker_user

WORKDIR /app/zcsim

# install requirements early for faster rebuilds
COPY zcsim/requirements.txt .
RUN pip3 install -r requirements.txt

COPY bin .
COPY zcsim .

ENV PYTHONPATH ..

